FROM python:3.10
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /fastapi
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY /fastapi .
EXPOSE 8000
CMD ["python", "./main.py"]