# Generated by Django 3.2.7 on 2021-09-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('patronymic', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('inn', models.IntegerField(null=True)),
                ('sex', models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], max_length=200, null=True)),
                ('dob', models.DateTimeField(null=True)),
                ('series_passport', models.IntegerField(null=True)),
                ('number_passport', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Old', 'Old')], max_length=200, null=True)),
                ('purchase_date', models.DateTimeField(null=True)),
                ('available', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], max_length=200, null=True),
        ),
    ]
