# Generated by Django 3.2.7 on 2021-09-23 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0002_auto_20210922_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='legalentity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.legalentity'),
        ),
        migrations.AddField(
            model_name='object',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.employee'),
        ),
        migrations.AddField(
            model_name='room',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coursework.object'),
        ),
    ]
