# Generated by Django 3.2.7 on 2021-09-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0005_alter_object_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='available',
        ),
    ]
