# Generated by Django 3.2.7 on 2021-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0009_auto_20210923_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='purchase_date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
