# Generated by Django 3.2.7 on 2021-09-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0010_alter_object_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='availability',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
