# Generated by Django 3.2.7 on 2021-09-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0011_object_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='employee_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
