# Generated by Django 3.2.7 on 2021-09-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0012_legalentity_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
