# Generated by Django 3.2.7 on 2021-09-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0013_alter_legalentity_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
    ]
