# Generated by Django 3.2.7 on 2021-09-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0019_alter_object_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='sex',
            field=models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], max_length=200, null=True),
        ),
    ]
