# Generated by Django 3.2.7 on 2021-10-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0021_object_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='qr_code',
        ),
    ]
