# Generated by Django 3.2.8 on 2022-01-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0022_remove_object_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='object',
            name='room',
        ),
    ]
