# Generated by Django 3.2.8 on 2022-01-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0023_auto_20220115_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='legalentity',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='sex',
        ),
    ]
